In [6]:
import numpy as np
import scipy
from scipy.fftpack import fft,ifft
#a
def circonv(g, h):
    if g.size != h.size:
        raise Exception("Sequences not of same length")
    N = g.size 
    htr=np.concatenate([[h[0]], h[:0:-1]])
    y=np.zeros(N)
    for n in np.arange(N):
        y[n]=np.sum(g*htr)
        htr=np.roll(htr,1)
    return y

In [7]:
#b
def modcirconv(g, h):
    if g.size != h.size:
        k=np.zeros(np.abs(g.size-h.size),dtype="int")
        if g.size>h.size:
            h=np.concatenate([h,k])
        else:
            g=np.concatenate([g,k])
    N = g.size 
    htr=np.concatenate([[h[0]], h[:0:-1]]) 
    y=np.zeros(N)
    for n in np.arange(N):
        y[n]=np.sum(g*htr)
        htr=np.roll(htr,1)
    return y

In [8]:
p=np.array([1,2,3,4,])
q=np.array([2,2,1,1])
circonv(p,q)

array([15., 13., 15., 17.])

In [5]:
#c
p=np.array([1,2,3,4,])
q=np.array([2,2,0,1,1])
modcirconv(p,q)

array([17., 13., 19., 20., 21.])

In [8]:
#d
P=fft(p)
Q=fft(q)
Y=ifft(P*Q)
print(Y)

[17.+0.j 13.+0.j 19.+0.j 20.+0.j 21.+0.j]


In [11]:
#e
a=scipy.linalg.circulant(q)
y=a@p
print(y)

[15 13 15 17]


In [6]:
#f
p=np.array([2,1,2,1])
q=np.array([1,2,3])
def conv(g,h):
    l1=g.size
    l2=h.size
    N=l1+l2-1
    n1=np.zeros(np.abs(N-l1-1),dtype="int")
    n2=np.zeros(np.abs(N-l2-1),dtype="int")
    h =np.concatenate([h,n1])
    g =np.concatenate([g,n2])
    y=modcirconv(g,h)
    return y
print(conv(p,q))

[ 2.  5. 10.  8.  8.  3.]


In [36]:
#h
g = np.concatenate([np.arange(128), np.arange(128,-1,-1)])
LHS = np.sum(g**2)
G = fft(g)
RHS = 1/G.size * np.sum(np.abs(G)**2)
print(LHS, RHS)

1398144 1398143.9999999998


In [50]:
#i
a=100*np.random.random_sample(500)
b=100*np.random.random_sample(500)
c=a + 1j*b
LHS = np.sum(np.abs(c**2))
G = fft(c)
RHS = 1/G.size * np.sum(np.abs(G)**2)
print(LHS, RHS)

3214495.577895778 3214495.577895778


In [5]:
g=np.array([1,1,1,0,0,0])
h=np.array([1,2,3,1,0,0])
print(circonv(g, h))

[1. 3. 6. 6. 4. 1.]
