In [1]:
import numpy as np
import math

In [2]:
def circonv(x,y):
    g=np.array(x)
    h=np.array(y)
    if g.size != h.size:
        raise Exception("Sequences not of same length")
    N = g.size 
    htr=np.concatenate([[h[0]], h[:0:-1]])
    y=np.zeros(N)
    for n in np.arange(N):
        y[n]=np.sum(g*htr)
        htr=np.roll(htr,1)
    Y=y.tolist()
    return Y

In [3]:
def os(sig,imp):
    M=len(imp)
    N=len(sig)+2*(M-1)
    L=N-M+1
    h=imp+[0]*(L-1)
    x_block=[0]*N
    Y=[]
    i=0
    j=0
    while i<len(sig):
        x_block=x_block[len(x_block)-M+1:]+sig[i:((j+1)*L)]
        i=(j+1)*L
        j=j+1
        if len(x_block)<N:
            x_block=x_block+[0]*(N-len(x_block))
        y_block=circonv(x_block,h)
        Y=Y+y_block[M-1:]
    return Y

In [4]:
sig1=[3,-1,0,1,3,2,0,1,2,1]
imp1=[1,1,1]
print(os(sig1,imp1))
print(np.convolve(sig1,imp1))
print("\n")
sig2=[2,-2,8,-2,-2,-3,-2,1,-1,9,1,3]
imp2=[1,-2,3]
print(os(sig2,imp2))
print(np.convolve(sig2,imp2))
print("\n")
sig3=[1,2,3,3,2,1,-1,-2,-3,5,6,-1,2,0,2,1]
imp3=[3,2,1,1]
print(os(sig3,imp3))
print(np.convolve(sig3,imp3))

[3.0, 2.0, 2.0, 0.0, 4.0, 6.0, 5.0, 3.0, 3.0, 4.0, 3.0, 1.0]
[3 2 2 0 4 6 5 3 3 4 3 1]


[2.0, -6.0, 18.0, -24.0, 26.0, -5.0, -2.0, -4.0, -9.0, 14.0, -20.0, 28.0, -3.0, 9.0]
[  2  -6  18 -24  26  -5  -2  -4  -9  14 -20  28  -3   9]


[3.0, 8.0, 14.0, 18.0, 17.0, 13.0, 4.0, -5.0, -13.0, 6.0, 23.0, 11.0, 15.0, 9.0, 7.0, 9.0, 4.0, 3.0, 1.0]
[  3   8  14  18  17  13   4  -5 -13   6  23  11  15   9   7   9   4   3
   1]


In [5]:
def oa(sig,imp):
    M=len(imp)
    N=len(sig)+1
    L=N-M+1
    h=imp+[0]*(L-1)
    x_block=[0]*N
    i=0
    j=0
    count=0
    while i<len(sig):
        i=(j+1)*L
        j=j+1
        count=count+1
    conv_mat=[]
    i=0
    j=0
    while i<len(sig):
        x_block=sig[i:((j+1)*L)]+[0]*(M-1)
        if len(x_block)!=len(sig)+1:
            x_block=x_block+[0]*(len(sig)+1-len(x_block))
        i=(j+1)*L
        y_block=circonv(x_block,h)
        conv_mat.append(y_block)
        j=j+1
    Y=[]
    k=0
    mid_block=[0]*(M-1)
    midblock_mat=[]
    while k+1<count:
        temp1=conv_mat[k]
        temp2=conv_mat[k+1]
        for l in range(M-1):
            mid_block[l]=temp1[N-M+1+l]+temp2[l]
        midblock_mat.append(mid_block)
        k=k+1
    for m in range(count):
        mat1=conv_mat[m]
        temp1=mat1
        if m==0:
            mat2=midblock_mat[m]
            temp2=mat2
            temp3=temp1[:N-M+1]+temp2
            Y=Y+temp3
        elif m==count-1:
            temp3=temp1[M-1:]
            Y=Y+temp3
        else:
            mat2=midblock_mat[m]
            temp2=mat2
            temp3=temp1[M-1:N-M+1]+temp2
            Y=Y+temp3
    return Y[:len(sig)+M-1]

In [6]:
sig1=[1,2,3,3,2,1,-1,-2,-3,5,6,-1,2,0,2,1]
imp1=[3,2,1,1]
print(oa(sig1,imp1))
print(np.convolve(sig1,imp1))
print("\n")
sig2=[3,-1,0,1,3,2,0,1,2,1]
imp2=[1,1,1]
print(oa(sig2,imp2))
print(np.convolve(sig2,imp2))
print("\n")
sig3=[2,-2,8,-2,-2,-3,-2,1,-1,9,1,3]
imp3=[1,-2,3]
print(oa(sig3,imp3))
print(np.convolve(sig3,imp3))

[3.0, 8.0, 14.0, 18.0, 17.0, 13.0, 4.0, -5.0, -13.0, 6.0, 23.0, 11.0, 15.0, 9.0, 7.0, 9.0, 4.0, 3.0, 1.0]
[  3   8  14  18  17  13   4  -5 -13   6  23  11  15   9   7   9   4   3
   1]


[3.0, 2.0, 2.0, 0.0, 4.0, 6.0, 5.0, 3.0, 3.0, 4.0, 3.0, 1.0]
[3 2 2 0 4 6 5 3 3 4 3 1]


[2.0, -6.0, 18.0, -24.0, 26.0, -5.0, -2.0, -4.0, -9.0, 14.0, -20.0, 28.0, -3.0, 9.0]
[  2  -6  18 -24  26  -5  -2  -4  -9  14 -20  28  -3   9]
